### ISSUE TITLE
Is this ready for consumption?

### ISSUE THREAD

**Issue by tapir** [OpenTire/OpenTire#5]
Is this tire model ready for serious projects?

**Comment by ho1** [comment]
@tapir, the Pacejka 2002 implementation has been vetted and produces results that line up with other (commercial) simulation tools. It has also been used in a number of serious projects (closed-source). Additionally, a Pacejka 2012 implementation is in the works and I hope to have it done in the next few weeks.

There can likely be some more work done on the interface to call the solver. Any feedback on the structure/layout of the solver API would be appreciated.

**Comment by tapir** [comment]
Glad to hear. What's different between Pacejka 2002 and 2012?

**Comment by tapir** [comment]
Also I don't see a camber angle on the tire state class. I thought magic formula took that into consideration?

**Comment by ho1** [comment]
Pacejka 2012 is published in the latest edition of Pacejka's book (Tire and Vehicle dynamics). The model definition has been extended to include inflation pressure changes and sections of camber effects are also reworked. 

The 'IA' in the tire state refers to inclination angle, which is another definition of camber angle (sign depends on which side of the vehicle the tire is mounted). 

Let me know if you have any more questions, I can use them to put together an FAQ for the project :)

**Comment by tapir** [comment]
I have one more :) Do you handle the low velocity divergence  of the magic formula or is it left to the user of the library?

**Comment by ho1** [comment]
Sorry for the late reply, currently low velocity issues are not address, nor are load/steer/camber limits (ie. FZMAX) capped within the evaluation.
